"""new fields in user model

Revision ID: 72168142b107
Revises: f1d6dc4c5f81
Create Date: 2022-04-06 11:09:03.470940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72168142b107'
down_revision = 'f1d6dc4c5f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
